import { mkdir, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"

import { probeCapabilities, type CapabilityEntry, type CapabilityMatrix } from "./probe-capabilities.js"

function renderCapabilitySection(title: string, entry: CapabilityEntry): string {
  return [
    `### ${title}`,
    `- status: \`${entry.status}\``,
    `- fallback: \`${entry.fallback}\``,
    `- verified_at: \`${entry.verified_at}\``,
    "- evidence:",
    ...entry.evidence.map((item) => `  - ${item}`),
    "",
  ].join("\n")
}

function renderCapabilityMatrixMarkdown(matrix: CapabilityMatrix): string {
  return [
    "# OpenCode Capability Matrix",
    "",
    "> Generated by `npm run probe:opencode` from the currently installed `@opencode-ai/plugin` surface and execution environment.",
    "",
    renderCapabilitySection("Overlay", matrix.overlay),
    renderCapabilitySection("Commands", matrix.commands),
    renderCapabilitySection("Hotkeys", matrix.hotkeys),
    renderCapabilitySection("Runtime Events", matrix.runtimeEvents),
    renderCapabilitySection("Theme Context", matrix.themeContext),
  ].join("\n")
}

async function main() {
  const matrix = await probeCapabilities({ liveHostAvailable: false })
  const outputPath = join(process.cwd(), "docs", "kanban-plugin", "opencode-capability-matrix.md")
  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, renderCapabilityMatrixMarkdown(matrix), "utf8")
}

void main()
